### ISSUE TITLE
Javadoc and links

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-junit5#1]
the classes don't have Javadoc and the Asciidoctor file does not point to the Javadoc when possible, for instance:

```
* `completeNow()` and `failNow(Throwable)` to notify of a success or failure
```

would point to the Javadoc.

**Comment by jponge** [comment]
Note to self: check the docgen / asciidoc integration like in https://github.com/vietj/vertx-materials/blob/master/src/main/asciidoc/Integrating_Netty.adoc

**Comment by jponge** [comment]
All done!

**Comment by jponge** [comment]
@vietj any further initial review, or can we move to a `master` branch now?

**Comment by vietj** [comment]
I'll redo a pass soon as last check and then I think we are good
