### ISSUE TITLE
Fail or warn when CountingCheckpoint#flag() is called too many times

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-junit5#10]
as this is clearly a test programming error the developer should not ignore

**Comment by jponge** [comment]
Your mileage varies on whether this is a problem or if you just wanted to meet an "at least" semantic.

How about having _exact_ vs _atLeast_ checkpoints?

**Comment by vietj** [comment]
atLeast is like a countdown latch ?

**Comment by jponge** [comment]
No, it would pass the checkpoint with at least a number of calls (and allow more) while exact would trigger a failure with more calls than specified.

**Comment by vietj** [comment]
perhaps we should make the exact version behave like a latch ? i.e exact number of flag(), that's often very useful (1 being the one we are talking about).
