### ISSUE TITLE
RunTestOnContext for JUnit 5

### ISSUE THREAD

**Issue by DavideD** [vert-x3/vertx-junit5#100]
There is this rule available for JUnit 4:
```
	@Rule
	public RunTestOnContext vertxContextRule = new RunTestOnContext();
```
It would be nice to have something similar for JUnit 5.
Probably an extension.

**Comment by jponge** [comment]
Good idea @DavideD, would you like to try to contribute it?

**Comment by DavideD** [comment]
I can try but I might need some help.
Can I copy the logic in Vert.x `RunTestOnContext`?
It seems it delegates some things to the VertxUnitRunner, should I do something similar and call the methods in VertxExtension?

**Comment by jponge** [comment]
I think yes you can copy or take inspiration from what's been done there.

**Comment by vietj** [comment]
@DavideD any progress on this contribution?

**Comment by DavideD** [comment]
No, sorry. I didn't have time

**Comment by tsegismont** [comment]
jUnit5 has a mechanism for [intercepting test method calls](https://junit.org/junit5/docs/current/user-guide/#extensions-intercepting-invocations).

This could be used to get a Vert.x context then run the test on this context.

@jponge the jUnit5 documentation says checkpoints shouldn't be used on Vert.x threads. Can you explain why?

This could be a problem if running tests on a Vert.x context.

**Comment by tsegismont** [comment]
Ok. Perhaps we should change the tip wording then, it is confusing.
