### ISSUE TITLE
Running tests individually from command line

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-junit5#13]
for instance:

```
> mvn test -Dtest=CountingCheckpointTest#smoke_test
```

run all tests but

```
> mvn test -Dtest=CountingCheckpointTest
```

works fine

**Comment by jponge** [comment]
It's a Maven Surefire thing, not supported with JUnit 5. http://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html#Running_a_Set_of_Methods_in_a_Single_Test_Class

**Comment by vietj** [comment]
@jponge makes sense, I was suspecting that but wasn't sure

**Comment by vietj** [comment]
too bad it was very convenient
