### ISSUE TITLE
CountingCheckpoint's triggers callbacks under lock

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-junit5#16]
CountingCheckpoint's triggers callbacks should be done outside of the synchronized block to avoid potential deadlocks.

**Comment by jponge** [comment]
Do you have a deadlock sequence in mind?

`CountingCheckpoint::flag` is `synchronized` on the `CountingCheckpoint` instance, and in our case the callbacks point to `VertxTestContext::checkpointSatisfied` and `VertxTestContext::failNow`, which are both `synchronized` on the `CountingCheckpoint` instance.

There is no lock-taking call from `VertxTestContext` to `CountingCheckpoint`.

**Comment by vietj** [comment]
this is more a recommendation I've done according to my experience and it does not have to be explicitly followed. According to the code there are chances we could elaborate an artificial case involving a checkpoint and two threads leading to a deadlock (i.e one thread is called back by the checkpoint and try to get another lock, while another thread holding this lock tries to flag the checkpoint concurrently). So we can close the issue if you like.

**Comment by jponge** [comment]
This is a very interesting discussion, I'm trying to figure what the problem could be in that specific callbacks combination 😉 

That being said I don't see any correctness issue by reducing the critical section either...

**Comment by vietj** [comment]
my experience is that callbacks under lock are potential deadlock sources and should be avoided when possible (https://github.com/eclipse/vert.x/issues/1834, )

**Comment by vietj** [comment]
now I agree we should not dogmatic about it
