### ISSUE TITLE
Stack integration

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-junit5#21]
todo (non exhaustive) list for integration in the stack:

- [x] initial-work PR
- [x] labelled as _tech preview_
- [x] snapshot publishing
- [x] integration in vertx-stack project (bom and documentation)
- [x] example in vertx-examples
- [x] web-site branch that publish documentation
- [x] blog post section for the release blog post that describes the feature and gives an example

**Comment by vietj** [comment]
ping @jponge

**Comment by jponge** [comment]
When's the deadline?

**Comment by vietj** [comment]
it would be good to have it done by end of next week.

**Comment by jponge** [comment]
@vietj on the first item (`initial-work` PR) there is not clean initial commit so the best is to just create a `master` branch from the `initial-work` state that is considered ok for you.

BTW I have no pending issue.

**Comment by vietj** [comment]
it should be alright now.

**Comment by jponge** [comment]
https://github.com/vert-x3/vertx-examples/pull/262

**Comment by jponge** [comment]
I'll create an initial 3.5.1 announcement blog post and add a small section on JUnit 5 here.

**Comment by jponge** [comment]
All done!

Thanks @vietj for the guidance.
