### ISSUE TITLE
Deployed Vertices is empty when launched with JUnit5

### ISSUE THREAD

**Issue by dadoonet** [vert-x3/vertx-junit5#25]
Not sure if it's an issue here or an issue from my code.

I have a `main` where I'm deploying the verticle like this:

```java
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        vertx.deployVerticle(new WebhookVerticle(
                Environment.target,
                Environment.port, Environment.token, Environment.root, Environment.branch, Environment.source), id -> {
            logger.debug("Webhook Verticle has been deployed {}", id);
            logger.info("{}", vertx.deploymentIDs());
        });
```

This prints:

```
19:00:05,117 INFO  [f.b.w.WebhookLauncher] [4f4b3701-44e3-45b7-a4d9-ae9e37799db0, 952373ca-fb31-418b-a16f-b17f534c3abb, a9fed1ba-c909-488e-a663-cfb13097493f]
```

When I do that in the context of a JUnit5 test:

```java
    @BeforeEach
    void startVertx(Vertx vertx, VertxTestContext testContext) {
        // Create Webhook Vertice
        WebhookVerticle webhookVerticle = buildWebhookVerticle();
        vertx.deployVerticle(webhookVerticle, testContext.succeeding(id -> {
            logger.info(" -> test webhook verticle deployed {}", id);
        }));
    }

    @Test
    void testVerticeHasBeenDeployed(Vertx vertx) {
        logger.info("{}", vertx.deploymentIDs());
        assertFalse(vertx.deploymentIDs().isEmpty());
    }
```

I'm getting:

```
19:05:11,438 INFO  [f.b.w.i.WebhookIT]  -> test webhook verticle deployed 03fd56ad-8c42-4811-b074-8439174d29ce
19:05:11,453 INFO  [f.b.w.i.WebhookIT] []
```

I don't understand why this is happening.
Note that I'm testing that with patch #23.

**Comment by dadoonet** [comment]
Yes. I'm creating this in a parent class though: 

https://github.com/brownbaglunch/java-webhook/blob/wip/add-more-it/src/test/java/fr/brownbaglunch/webhook/it/AbstractIT.java#L133-L141

**Comment by vietj** [comment]
I can't see in the code you show where the deploymentIDs() is used

**Comment by dadoonet** [comment]
I created this test class:

```java
package fr.brownbaglunch.webhook;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@ExtendWith(VertxExtension.class)
class VertxTest {
    private final Logger logger = LogManager.getLogger(this.getClass());

    @BeforeEach
    void deployVertice(Vertx vertx, VertxTestContext testContext) {
        vertx.deployVerticle(new FakeVertice(), testContext.succeeding(id -> {
            logger.info(" -> test webhook verticle deployed {}", id);
            logger.info("deployVertice {}", vertx.deploymentIDs());
        }));
    }

    @Test
    void testDeployVertice(Vertx vertx, VertxTestContext testContext) {
        logger.info("testDeployVertice {}", vertx.deploymentIDs());
        assertFalse(vertx.deploymentIDs().isEmpty());
    }

    static class FakeVertice extends AbstractVerticle {    }
}
```

Note that I had to add a `testContext.succeeding()` in the BeforeEach method in case it helps but no luck...

Looks like there is kind of race condition as sometimes I'm seeing:

```
09:21:28,826 INFO  [f.b.w.VertxTest]  -> test webhook verticle deployed a6de02ca-63eb-41f0-8c81-352ba7c219b2
09:21:28,828 INFO  [f.b.w.VertxTest] deployVertice [a6de02ca-63eb-41f0-8c81-352ba7c219b2]
09:21:28,826 INFO  [f.b.w.VertxTest] testDeployVertice []
```

And sometimes, this:

```
09:21:53,846 INFO  [f.b.w.VertxTest]  -> test webhook verticle deployed bff1670c-4b37-42b7-9007-e8a02e08fc96
09:21:53,846 INFO  [f.b.w.VertxTest] testDeployVertice []
09:21:53,849 INFO  [f.b.w.VertxTest] deployVertice [bff1670c-4b37-42b7-9007-e8a02e08fc96]
```

Anyway in all cases, the test fails as deployed vertices as seen by the test method is always empty.

**Comment by jponge** [comment]
It's likely because each injection (`@BeforeAll`, `@Test`, etc) of `Vertx` creates a new instance, so your test methods don't see the same instance.

Need to check, but then a sane behavior would be to have 1 `Vertx` instance per extension context, and 1 `VertxTestContext` per injection.

**Comment by dadoonet** [comment]
> It's likely because each injection (`@BeforeAll`, `@Test`, etc) of `Vertx` creates a new instance, so your test methods don't see the same instance.

But in my example, I just have one single test.

```
@ExtendWith(VertxExtension.class)
class VertxTest {
    @BeforeEach
    void deployVertice(Vertx vertx, VertxTestContext testContext) {  /* ... */  }

    @Test
    void testDeployVertice(Vertx vertx, VertxTestContext testContext) {  /* ... */  }
}
```

What is your suggestion then?

**Comment by dadoonet** [comment]
> I'll let you know when I have checked, but the fix is likely on us ;-)

Ha cool! I thought I had to change something on my side. :)

**Comment by jponge** [comment]
@vietj Why do you have before each / before all tests but the extension does not implement the before all callback?

**Comment by vietj** [comment]
agreed for the management @jponge

**Comment by vietj** [comment]
@jponge which callback are missing ?

**Comment by vietj** [comment]
@jponge why isn't the same vertx instance injected ? perhaps it should be reused between contexts ?

**Comment by vietj** [comment]
so basically vertx would be set on the extension class and reused

**Comment by jponge** [comment]
@vietj I'm looking at it, but I've reproduced and applied a first fix. I'm on making it complete and see if I need to refactor more of how the lifecycle is managed following the addition of `@BeforeXYZ`.

1. There is a callback for each stage, including `BeforeAll` but that callback hasn't been addressed.
2. The await completion method you introduced is called for each stage now, but parameter injection hasn't been touched, so for each stage there are new objects being created.

**Comment by jponge** [comment]
@dadoonet 

I'm green with that:

```java
static class UselessVerticle extends AbstractVerticle {}

  @Nested
  @ExtendWith(VertxExtension.class)
  class VertxInjectionTest {

    @BeforeEach
    void prepare(Vertx vertx, VertxTestContext testContext) {
      vertx.deployVerticle(new UselessVerticle(), testContext.succeeding());
    }

    @AfterEach
    void cleanup(Vertx vertx, VertxTestContext testContext) {
      assertThat(vertx.deploymentIDs()).isNotEmpty().hasSize(1);
      vertx.close(testContext.succeeding());
    }

    @RepeatedTest(10)
    void checkDeployments(Vertx vertx, VertxTestContext testContext) {
      assertThat(vertx.deploymentIDs()).isNotEmpty().hasSize(1);
      testContext.completeNow();
    }

    @Nested
    class NestedTest {
      @RepeatedTest(10)
      void checkDeployments(Vertx vertx, VertxTestContext testContext) {
        assertThat(vertx.deploymentIDs()).isNotEmpty().hasSize(1);
        testContext.completeNow();
      }
    }
  }
```

Push coming soon, plus I've added support for `@AfterEach` in the lifecycle.

**Comment by jponge** [comment]
All good now

**Comment by WantSomeKnowledge** [comment]
how can i set log4j for my junit? i want it to log the logs of my services

**Comment by jponge** [comment]
See https://vertx.io/docs/apidocs/io/vertx/core/logging/Logger.html for the system properties to activate a specific logger for Vert.x.

There is nothing special to do for JUnit5, but you may look at https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-logging for the system property to activate (with Gradle).

**Comment by WantSomeKnowledge** [comment]
thank you so much! yeah it was normal; i didn't pay attention, i thought it
would be different than how i configure it usually


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/10/18
à 16:49:00

Le ven. 5 oct. 2018 à 13:11, Julien Ponge <notifications@github.com> a
écrit :
