### ISSUE TITLE
Failed assertions don't mark the test as failed

### ISSUE THREAD

**Issue by dadoonet** [vert-x3/vertx-junit5#26]
I'm testing a Webservice which is doing a `POST /_validate`.
This service returns a 400 status code.

I wrote the following code:

```java
    @Test
    void testPostValidate(Vertx vertx, VertxTestContext testContext) {
        WebClient webClient = WebClient.create(vertx,
                new WebClientOptions()
                        .setDefaultHost("localhost")
                        .setDefaultPort(HTTP_PORT));
        HttpRequest<Buffer> request = webClient.post("/_validate");
        request.send(testContext.succeeding(result -> testContext.verify(() -> {
            logger.fatal("CODE {}", result.statusCode());
            assertEquals(200, result.statusCode());
        })));
    }
```

This is producing, which shows that the error code is `400`:

```
17:29:31,071 FATAL [f.b.w.i.WebhookVerifyBadContentlIT] CODE 400
```

But the test never fails JUnit and I don't understand why. I think I followed instructions [there](https://github.com/vert-x3/vertx-junit5/blob/master/src/main/asciidoc/output/index.adoc#use-any-assertion-library) though.

![image](https://user-images.githubusercontent.com/274222/35196427-288a5a74-fed2-11e7-9d6b-cb634d9ae247.png)

**Comment by dadoonet** [comment]
Here is an even easier thing:

```java
@ExtendWith(VertxExtension.class)
class VertxTest {

    @Test
    void testTrue(Vertx vertx, VertxTestContext testContext) {
        testContext.verify(() -> {
            assertTrue(false);
        });
    }
}
```

But may be my understanding is wrong.

**Comment by vietj** [comment]
hi, you should use completeNow() in the verify block instead

```
    @Test
    void testTrue(Vertx vertx, VertxTestContext testContext) {
        testContext.verify(() -> {
            assertTrue(false);
            testContext.completeNow(); // Probably not necessary.
        });
    }
```

**Comment by dadoonet** [comment]
So I ran this:

```java
@ExtendWith(VertxExtension.class)
class VertxTest {

    @Test
    void testTrue(Vertx vertx, VertxTestContext testContext) {
        testContext.verify(() -> {
            assertTrue(false);
            testContext.completeNow();
        });

    }
}
```

And got: 

![image](https://user-images.githubusercontent.com/274222/35210545-f607c18c-ff52-11e7-9d4d-987c4b8b6ca8.png)

Can we reopen?

**Comment by vietj** [comment]
I think we can

**Comment by vietj** [comment]
`assertTrue ` is junit assertion static method ?

**Comment by dadoonet** [comment]
@vietj It is `org.junit.jupiter.api.Assertions.assertTrue`:

```java
import static org.junit.jupiter.api.Assertions.assertTrue;
```

**Comment by vietj** [comment]
thanks for reporting, going to investigate soon

**Comment by vietj** [comment]
@jponge how an asynchronous test is supposed to fail ? `VertxTestContext#awaitCompletion` only await the test finish but does not check the `throwableReference` field.

**Comment by jponge** [comment]
Let me have a look.

**Comment by jponge** [comment]
It reduces to:

```java
@Nested
  @ExtendWith(VertxExtension.class)
  class FailureTest {

    @Test
    void testTrue(Vertx vertx, VertxTestContext testContext) {
      testContext.verify(() -> {
        assertTrue(false);
      });
    }
  }
```

**Comment by jponge** [comment]
A fix is coming @dadoonet

**Comment by jponge** [comment]
Here you go

**Comment by jponge** [comment]
Looking at the @vietj 's PR

**Comment by AlexLi-Monster** [comment]
> A fix is coming @dadoonet

Hi @jponge ,

May I ask which version has the fix? I am still having the problem on version `3.8.5`

Thanks,
Alex

**Comment by jponge** [comment]
3.9.1 / 4.0.0

**Comment by AlexLi-Monster** [comment]
> 3.9.1 / 4.0.0

Thanks!
