### ISSUE TITLE
Close created Vertx instances

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-junit5#27]
Currently the VertxExtension injects Vertx instance in the various test methods.

Such instance should be closed when the test has finished, because it consumes OS file descriptors.

For instance if we run a test method injected with a Vertx instance and we repeat the test enough time then the test OS will run out of file descriptor.

**Comment by jponge** [comment]
So what if you have:

```java
@AfterEach(Vertx vertx, VertxTestContext context) {
  // ...
}
```

**Comment by jponge** [comment]
Nevermind, we can close in `AfterEachCallback`

**Comment by jponge** [comment]
Done
