### ISSUE TITLE
Enable Java 9 Travis-CI again when Maven Surefire has been fixed

### ISSUE THREAD

**Issue by jponge** [vert-x3/vertx-junit5#29]
https://github.com/junit-team/junit5/issues/1188

**Comment by mxmind** [comment]
Seems, it is ready to close? Right?

**Comment by jponge** [comment]
No, because Surefire 2.19.1 only works with a `-SNAPSHOT` of JUnit.

**Comment by jponge** [comment]
Sorry 2.21

**Comment by mxmind** [comment]
Yet, another question. Does it work fine with gradle, or not?

**Comment by jponge** [comment]
I believe so

**Comment by mxmind** [comment]
Excellent, thanks a million.

**Comment by jponge** [comment]
Finally!
