### ISSUE TITLE
Add support for RxJava

### ISSUE THREAD

**Issue by shvalb** [vert-x3/vertx-junit5#33]
Same as  vertx-rxjava - very useful and makes the flow more consistent and easy to follow.

**Comment by vietj** [comment]
can you elaborate, it's unclear to me how it could support RxJava ?

**Comment by shvalb** [comment]
for example, there is the Vertx core library and you have the vertx-rxjava which is like a rxified version...
I hope I define it right.

**Comment by vietj** [comment]
I see, but we have chosen for vertx junit5 to not be polyglot and thus there is no code generation for it, it should be used as is with Java interrop' friendly JVM languages

**Comment by jponge** [comment]
Do you mean that you would like to have injection of, say, `io.vertx.reactivex.core.Vertx` and not just `io.vertx.core.Vertx`?

You can already use RxJava 1 or 2 with this library, you can always create a `Vertx` context yourself and/or wrap a `io.vertx.core.Vertx` into a `io.vertx.reactivex.core.Vertx`.

**Comment by shvalb** [comment]
I guess, your suggestion of wrapping it with io.reactivex.core.Vertx will
do.

Thanks.

**Comment by jponge** [comment]
@shvalb see #34
