### ISSUE TITLE
VertxExtension should also inject io.vertx.reactivex.core.Vertx

### ISSUE THREAD

**Issue by cvgaviao** [vert-x3/vertx-junit5#36]
When trying to test a Verticle that extends `io.vertx.reactivex.core.AbstractVerticle` I received:
`org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter ` 

Seems that the io.vertx.junit5.VertxExtension class was created to inject only objects from `io.vertx.core.Vertx`

**Comment by jponge** [comment]
This has been changed in current `master` branch, see #34

**Comment by jponge** [comment]
We should soon have a first milestone out (ping @vietj)
