### ISSUE TITLE
https://vertx.io/docs/vertx-junit5-web-client/java/ 404 Page not found

### ISSUE THREAD

**Issue by julianladisch** [vert-x3/vertx-junit5#66]
https://vertx.io/docs/vertx-junit5/java/#_junit_5_additional_extensions contains the link "Vert.x Junit 5 Web Client" pointing to https://vertx.io/docs/vertx-junit5-web-client/java/ but that URL returns 404 Page not found/File not found.

**Comment by jponge** [comment]
@slinkydeveloper We had discussed this but I don't remember the conclusion. Was it that we did not merge it into the 3.8 branches?

**Comment by slinkydeveloper** [comment]
I don't know the website snapshot link to put there, @vietj

**Comment by vietj** [comment]
https://vertx-ci.github.io/web-site-snapshot/

**Comment by slinkydeveloper** [comment]
So it should be accessible at https://vertx-ci.github.io/web-site-snapshot/docs/vertx-junit5-web-client/java/, but is not :thinking:

**Comment by vietj** [comment]
you can build the web site to check yourself and see what is wrong

**Comment by slinkydeveloper** [comment]
@vietj Looks like i've found the issue. the vertx-ci web site builds are not based on this branch, right? https://github.com/vert-x3/vertx-web-site/tree/vertx-4-preview
There is an address where this version of website is accessible?

**Comment by jponge** [comment]
Since the web client has moved to the Reactiverse, I'm closing this one.

**Comment by IcyTv** [comment]
Okay, but where is the documentation for the JUnit5 web client now? Cause I cant find any documentation except [here](https://vertx-ci.github.io/vertx-4-preview/docs/apidocs/io/vertx/junit5/web/TestRequest.html) but there are a bunc of explanations missing and the webpage for the containing package (io.vertx.junit5.web) is not there either...

**Comment by jponge** [comment]
In this repository, and there will soon be a webpage https://github.com/reactiverse/reactiverse-junit5-extensions
