### ISSUE TITLE
Milestone5 => "No parameter resolver" for rx* classes

### ISSUE THREAD

**Issue by aesteve** [vert-x3/vertx-junit5#82]
### Version

4.0.0-milestone5

### Context

When upgrading a project using `vertx-rx-java2` to milestone5, tests did not work anymore, because `io.vertx.reactivex.core.Vertx` has no parameter resolver.

### Do you have a reproducer?

* https://github.com/aesteve/junit5-milestone5-reproducer

### Steps to reproduce

1. Just run the test task from the reproducer

### Extra

* The original project where it happened was a Kotlin project, so I started with a Kotlin reproducer, then added a Java test class to show the issue was also happening in Java

**Comment by jponge** [comment]
Hi @aesteve, did you try adding dependency `vertx-junit5-rx-java2` from https://github.com/vert-x3/vertx-rx/tree/master/rx-junit5-providers?

This was documented in the breaking changes.

**Comment by aesteve** [comment]
I'll try that. Thank you.

I was almost sure I missed something, asked on Gitter, and have been asked to open an issue, sorry for the noise.

**Comment by jponge** [comment]
No worries, closing the issue, please re-open if you spot any issue 👍

**Comment by aesteve** [comment]
Works indeed. Updating the repo + README
