### ISSUE TITLE
rxjava2: reactive Vertx should be injected in Junit 5

### ISSUE THREAD

**Issue by hantsy** [vert-x3/vertx-junit5#95]
In Vertx Rxjava 2 sample, I tried to use all vertx-rx-rxjava2 APIs instead of the vertex core.

But the `io.vertx.reactivex.core.Vertx` can not be injected in the JUnit 5 methods like the normal Vertx. 

My application is based on the following stack:

* Vertx 4.0.0
* Java 11
* Windows 10

I have to wrap it [myself like this](https://github.com/hantsy/vertx-sandbox/blob/master/rxjava2/src/test/java/com/example/demo/TestMainVerticle.java#L48):

```java
WebClient client = WebClient.create(new io.vertx.reactivex.core.Vertx(vertx));
```

**Comment by vietj** [comment]
which vertx version ?

**Comment by hantsy** [comment]
>Vertx 4.0.0

**Comment by vietj** [comment]
@jponge ?

**Comment by jponge** [comment]
As documented in the release notes, you need to add a dependency on https://github.com/vert-x3/vertx-rx/tree/master/rx-junit5-providers/vertx-junit5-rx-java2

**Comment by hantsy** [comment]
@jponge @vietj  Thanks.
